---
title: "Facebook粉絲團分析 蔡英文Tsai Ing-wen"
output: github_document
分析蔡英文紛絲專頁，資料分析區間為2016/01/01至 2016/04/10
---
if (!require('Rfacebook')){
    install.packages("Rfacebook")
    library(Rfacebook)
}
```{r }
## 讀取蔡英文粉絲團資料

token<-'CAAQq4AUOaVMBAFiZAZCbRLEWD2G5kHJTZB7WHjSTNQKCZCfpHC1k6ZC9DZBOL27E9VJsl2KbDT6YaFtWnZBrxC59gQ3LwZBZCaw6ckSQyvHpHvzoM1ZAhgxonCTyyAtFI22ZCjMZCk6hhqJiKMavm5I38rckci8QoYRdv78HkdXXMRgHThxz0gBTRIwdPuRwkfqVlT66Sk9VZAZCZBgZBQZDZD'
totalPage<-NULL
lastDate<-Sys.Date()
DateVectorStr<-as.character(seq(as.Date("2016-01-01"),lastDate,by="5 days"))
for(i in 1:(length(DateVectorStr)-1)){
    tempPage<-getPage("TsaiIngwen", token,
                      since = DateVectorStr[i],until = DateVectorStr[i+1])
    totalPage<-rbind(totalPage,tempPage)
}
nrow(totalPage)
```



```{r }
## 每日發文數分析

totalPage$datetime <- as.POSIXct(totalPage$created_time, 
                                 format = "%Y-%m-%dT%H:%M:%S+0000", 
                                 tz = "GMT") #2016-04-10T15:05:36+0000
totalPage$dateTPE <- format(totalPage$datetime, "%Y-%m-%d", 
                            tz = "Asia/Taipei") #2016-04-10

totalPage$weekdays <-weekdays(as.Date(totalPage$dateTPE))
PostCount<-aggregate(id~dateTPE,totalPage,sum)
library(knitr)
kable(head(PostCount[order(PostCount$id,decreasing = T),]))

```
討論:1/11和1/16發文數最多,而那幾天因為是總統大選前夕所以比平常多

```{r }
## 每日likes數分析
likescount<-aggregate(likes_count~dateTPE,totalPage,sum)
library(knitr)
kable(head(likescount[order(likescount$likes_count,decreasing = T),]))
```
討論:1/16那天一百多萬讚最多,其次是1/15五十多萬讚
```{r }
## 每日comments數分析
commentscount<-aggregate(comments_count~dateTPE,totalPage,sum)
library(knitr)
kable(head(commentscount[order(commentscount$comments_count,decreasing = T),]))
```
討論:1/20留言數最多55萬多筆,其次是1/16的49萬筆
```{r }
## 每日shares數分析
sharescount<-aggregate(shares_count~dateTPE,totalPage,sum)
library(knitr)
kable(head(sharescount[order(sharescount$shares_count,decreasing = T),]))
```
討論:1/16分享數最多有2萬5千多筆,其次是1/15的1萬8千多筆

