---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---
  
```{r echo=T}  
install.packages("SportsAnalytics")
library(SportsAnalytics)
NBA1415<-fetch_NBAPlayerStatistics("14-15")
names(NBA1415)
head(NBA1415)
nrow(NBA1415)
ncol(NBA1415)
```
## 各隊最辛苦的球員

計算「總出場分鐘數」最多的球員

```{r echo=T}
TotalMinutesPlayed<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
NBA1415TotalMinutesPlayed<-merge(NBA1415,TotalMinutesPlayed)
output<-NBA1415TotalMinutesPlayed[order(NBA1415TotalMinutesPlayed$TotalMinutesPlayed,decreasing=T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digit=2)
```

## 各隊得分王

計算各隊「總得分」最多的球員
```{r echo=T}
MaxPoint<-aggregate(TotalPoints~Team,NBA1415,max)
NBA1415MaxPoint<-merge(NBA1415,MaxPoint)
output<-NBA1415MaxPoint[order(NBA1415MaxPoint$TotalPoints,decreasing=T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digit=2)
```

##各隊最有效率的球員

計算「總得分/出戰分鐘數」最高的球員
```{r echo=T}
NBA1415$effect<-
    round(NBA1415$TotalPoints/NBA1415$TotalMinutesPlayed,digits=2)
Maxeffect<-merge(NBA1415,aggregate(effect~Team,NBA1415,max))
Maxeffect[order(Maxeffect$effect,decreasing=T),
           c("Team","Name","Maxeffect")]

```
##各隊三分球出手最準的球員

計算「三分球/三分球出手數」最高的球員
```{r echo=T}
NBA1415$ThreesP<-
    round(NBA1415$ThreesMade/NBA1415$ThreesAttempted,digits=2)
ThreesPMax<-merge(NBA1415,aggregate(ThreesP~Team,NBA1415,max))
ThreesPMax[order(ThreesPMax$ThreesP,decreasing=T),
           c("Team","Name","ThreesP")]
```